"""Database models and schemas."""

from app.models.database import (
    Base,
    Video,
    AnalysisJob,
    Transcription,
    TranscriptionSegment,
    Diarization,
    DiarizationSegment,
    Scene,
    ClipSuggestion,
    Hook,
    get_async_session,
    get_sync_session,
    init_db,
)
from app.models.schemas import (
    VideoCreate,
    VideoResponse,
    VideoDownloadRequest,
    AnalysisJobResponse,
    AnalysisStartRequest,
    AnalysisStatusResponse,
    AnalysisFullResponse,
    ClipSuggestionResponse,
    ClipExportRequest,
    TranscriptionResponse,
    DiarizationResponse,
    SceneResponse,
    HookResponse,
    ViralityScore,
)

__all__ = [
    # Database
    "Base",
    "Video",
    "AnalysisJob",
    "Transcription",
    "TranscriptionSegment",
    "Diarization",
    "DiarizationSegment",
    "Scene",
    "ClipSuggestion",
    "Hook",
    "get_async_session",
    "get_sync_session",
    "init_db",
    # Schemas
    "VideoCreate",
    "VideoResponse",
    "VideoDownloadRequest",
    "AnalysisJobResponse",
    "AnalysisStartRequest",
    "AnalysisStatusResponse",
    "AnalysisFullResponse",
    "ClipSuggestionResponse",
    "ClipExportRequest",
    "TranscriptionResponse",
    "DiarizationResponse",
    "SceneResponse",
    "HookResponse",
    "ViralityScore",
]
